extends: airbnb-base
parserOptions:
  ecmaVersion: 5
rules:
  indent: ["error", "tab"]
  no-tabs: 0
  no-console: 0
  eol-last: 0
  arrow-parens: 0
  keyword-spacing: 0
  arrow-body-style: 0
  max-len: [2, { "code": 200 }]
  import/no-dynamic-require: 0
  class-methods-use-this: 0
  dot-notation: 0
  no-param-reassign: 0
  no-underscore-dangle: 0
  no-plusplus: 0